spring.application.name=ledgerpay

spring.datasource.url=jdbc:postgresql://localhost:5432/ledgerpay
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
jwt.secret=P1VMQazoPXHdlIXmfqTgF2ci/7//lKVsoPoo52k8Q58=
jwt.expiration-ms=3600000

